joy-game/src/App.css
joy-game/src/App.tsx
joy-game/src/components/Dice.tsx
joy-game/src/components/Game.tsx
joy-game/src/components/Player.tsx

Added dice, player, and game into components and added the game into the app.tsx file

Game skeleton

---

joy-game/src/App.tsx
joy-game/src/logic.ts

each player starts with 5 dice & sees own dice, sees other player's dice counts.  Can roll each die individually by clicking.  Yay.

Suz multiplayer simplified

---

joy-game/src/App.tsx
joy-game/src/logic.ts

roll all dice button works for each player!

111 roll all dice

---

joy-game/src/components/GameZone.css
joy-game/src/components/GameZone.tsx

tried to mirror joels code - I think two paragraphs need to be swapped in the bottom section, but I'm going to see if this allows for the merge to happen smoothly

911 revive main frankenstein

---

joy-game/src/components/Dice.tsx

imported all dice images, created an array, and loaded dynamically in img source at the Dice component.

fixing images request

---

advance-game/src/App.css
advance-game/src/App.tsx
advance-game/src/components/Gamezone.css
advance-game/src/components/Gamezone.tsx
advance-game/src/components/SideScrollerGame.js
advance-game/src/demoFiles/AltApp.js
advance-game/src/demoFiles/AltIndex.html
advance-game/src/demoFiles/AltMain.ts
advance-game/src/demoFiles/Canvas.css
advance-game/src/demoFiles/InputButton.ts
advance-game/src/demoFiles/Player.ts
advance-game/src/index.css

combining code from chris and andrew

Merged collab work

---

joy-game/src/components/Controls.tsx
joy-game/src/components/Table.tsx
joy-game/src/logic.ts

173 cake branch prev player

---

joy-game/src/components/Credits.css
joy-game/src/components/Credits.tsx
joy-game/src/components/GameZone.tsx
joy-game/src/components/HelpPopup.tsx

added credit component to show credits on popup

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.css
battle-sweep/src/components/Board.tsx
battle-sweep/src/components/Tile.css
battle-sweep/src/components/Tile.tsx
battle-sweep/src/helper/BoardCreation.tsx
battle-sweep/src/logic.ts

Adding bomb counter code and meshing into to rune server build

Adding bomb counter code

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.tsx
battle-sweep/src/logic.ts

adding some multi-player functionality

Add boards to player objects

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.tsx
battle-sweep/src/components/Controls.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/logic.ts

swap city, is ready, once timer is reverted

Adding board swap action and button

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/components/Tile.tsx
battle-sweep/src/helper/BoardCreation.tsx
battle-sweep/src/logic.ts

added event handler function to check when user tries to flip a tile. 
updated actions with flip switch statement to flip cell, check if bomb, or check if 0 and expand additional tiles.
added gameover function when user clicks bomb

Flip hidden tiles when pressed

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/helper/BoardCreation.tsx
battle-sweep/src/helper/Types.ts
battle-sweep/src/logic.ts

Adding a basic score functionality!

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Board.tsx
battle-sweep/src/components/InPlay.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/logic.ts

add single player auto game start
also shows message to second player if join after game has begun. Message does nothing now, but could make it a modal and block user interaction until their single player game ends
also tiny fix with the swap feature to add bombs if amount placed is less than required

Adds handling for single player

---

battle-sweep/src/components/Config.tsx
battle-sweep/src/helper/Types.ts

Merged b002 and b032 into main and corrected minor compiling issues

B039 resolved merged main patching

---

battle-sweep/src/components/Controls.tsx
battle-sweep/src/components/Timer.tsx
battle-sweep/src/logic.ts

Changed game.onboarding to equal false instead of just not what state it used to be in

fixed circular swapping bug

---

battle-sweep/src/components/Controls.tsx
battle-sweep/src/components/Timer.tsx
battle-sweep/src/helper/Types.ts
battle-sweep/src/logic.ts

Removed use effect and action calls in timer.tsx. 
Implemented timer changes directly into update.
added timer for game rounds
changed min players to two until onboard screen ready

Expand timer

---

battle-sweep/src/helper/BoardCreation.tsx
battle-sweep/src/helper/Types.ts
battle-sweep/src/logic.ts

added player states for time taken on turn and if their turn has ended (based on clicking a bomb, or revealing all bombs). Previous game end events
switched game end events to be turn end events, and waiting for timer to run out

Add time based scoring component

---

battle-sweep/src/App.tsx
battle-sweep/src/components/OpponentBoard.css
battle-sweep/src/components/OpponentBoard.tsx
battle-sweep/src/components/OpponentTile.css
battle-sweep/src/components/OpponentTile.tsx

Added miniboard .  Board should not be visible during onboarding and appear once game starts.

B033  add miniboard to see opponents progress

---

battle-sweep/src/components/Credits.tsx
battle-sweep/src/components/HelpPopup.css
battle-sweep/src/components/HelpPopup.tsx

Added game synopsis and how to play.  Updated credits page with accurate information based on information provided.

B900   update credits page

---

battle-sweep/src/components/HelpPopup.tsx
battle-sweep/src/components/Player.tsx

I used the proposed new name 'Catch the Crabs" for the game and modified the instructions accordingly. Any of it can easily be changed again if we decide on a different name.

Changed the instructions to match the theme.

---

battle-sweep/src/App.tsx
battle-sweep/src/helper/Types.ts
battle-sweep/src/logic.ts

fixed timer issues, and based new timers to start when player presses start.
also changed min player back to one, and updated time durations to be more realistic

Don't start timer actions until player clicks start

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Controls.tsx
battle-sweep/src/components/HelpPopup.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/components/StyledBoard.tsx

Changed references to bombs to crabs and other theme related changes. Added the feature request made by producer.

B060 additional themeing

---

battle-sweep/src/App.tsx
battle-sweep/src/components/Player.tsx
battle-sweep/src/components/StartPage.tsx
battle-sweep/src/components/StyledBoard.tsx
battle-sweep/src/components/Tile.css

_could be merged, or I can keep working on it in this branch._
I separated out start menu into it's own return to reduce branching. This has no impact in UI, just readability.
for spectator view, you can only see avatar and some controls. because I have only updated player

Adjusting layout for new theme

---

battle-sweep/src/App.tsx
battle-sweep/src/logic.ts

when a player joins and starts a game, when player two joins, they're in the game.
now, if a player two joins mid game, we provide them an auto generated board. otherwise same as before

B502 handle mid game player two

---

battle-sweep/src/App.tsx

if player ones turn ends and player two is still playing, show a waiting for opponent message and preview opponents board

Add opponent waiting message

---

battle-sweep/src/App.css
battle-sweep/src/App.tsx
battle-sweep/src/components/Timer.css
battle-sweep/src/components/Timer.tsx

Number players needs to change when player exits, and adding sprite counter

---

joy-game/README.md
joy-game/package-lock.json
joy-game/package.json
joy-game/src/components/GameZone.tsx
joy-game/src/logic.ts

Added a phrase to the readme to test connection
Update Rune SDK to allow for 6 players
Added 2 Divs: player 5 and player 6. Still needs work, but they exist now. 
noticed 'newGame' does not exist as a parameter in 'game' so it's throwing a typescript error. We'll need to fix that before releasing our update.

Readme test branch k
